# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""
Qdrant search indexer for ColPali embeddings.

This module provides a Qdrant-based search indexer that supports ColPali
multi-modal embeddings with optimized pooling strategies and async I/O operations.
The implementation is based on the Qdrant documentation for PDF retrieval at scale:
https://qdrant.tech/documentation/advanced-tutorials/pdf-retrieval-at-scale/

The indexer supports multiple embedding strategies:
- Original embeddings (hierarchical patches with HNSW disabled for exact search)
- Mean pooling by rows (aggregated row-wise embeddings)
- Mean pooling by columns (aggregated column-wise embeddings)

Environment Variables:
    QDRANT_ENDPOINT: Qdrant service endpoint URL
    QDRANT_API_KEY: Optional API key for Qdrant authentication
"""

import asyncio
import json
import logging
import os
from typing import List, Optional

import numpy as np
from azure.identity.aio import DefaultAzureCredential, ManagedIdentityCredential
from qdrant_client import AsyncQdrantClient, models
from tenacity import (
    RetryCallState,
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_fixed,
)

from .models import ProcessedPage


class QdrantIndex:
    """
    Qdrant search indexer supporting ColPali multi-modal embeddings.

    This class provides an async interface to Qdrant for indexing and searching
    document embeddings generated by ColPali models. It supports multiple
    embedding strategies including original patch-based embeddings and pooled
    representations for different search scenarios.

    Features:
    - Async I/O operations using AsyncQdrantClient for non-blocking performance
    - Multi-vector configuration with different pooling strategies
    - Automatic collection management and schema creation
    - Document-level deletion support
    - Azure credential integration for managed identity authentication

    Qdrant Schema:
    - Collection: "colpali-documents"
    - Vectors:
        * "original": Hierarchical patch embeddings (HNSW disabled for exact search)
        * "mean_pooling_rows": Row-wise aggregated embeddings
        * "mean_pooling_columns": Column-wise aggregated embeddings
    - Distance: COSINE similarity
    - Comparator: MAX_SIM for multi-vector matching

    Attributes:
        qdrant_client: Async Qdrant client instance
        credential: Azure credential for authentication
        collection_name: Fixed collection name for document storage
        qdrant_endpoint: Qdrant service endpoint URL
    """

    def __init__(
        self,
        credential: Optional[DefaultAzureCredential | ManagedIdentityCredential] = None,
        require_endpoint: bool = True,
    ):
        """
        Initialize Qdrant client based on environment configuration.

        Args:
            credential: Azure credential for authentication. If None, uses DefaultAzureCredential
            require_endpoint: Whether to require QDRANT_ENDPOINT environment variable.
                            Set to False for local development/testing scenarios

        Raises:
            ValueError: If require_endpoint is True but QDRANT_ENDPOINT is not set,
                       or if Qdrant client initialization fails in production mode
        """
        self.qdrant_client = None
        self.credential = credential or DefaultAzureCredential()
        self.collection_name = "colpali-documents"
        self.vectors_config = self._get_default_vectors_config()
        self.qdrant_endpoint = os.getenv("QDRANT_ENDPOINT")

        # Qdrant concurrency and batching configuration
        self.max_concurrent_upserts = int(os.getenv("QDRANT_MAX_CONCURRENT", "5"))
        self.upsert_batch_size = int(os.getenv("QDRANT_BATCH_SIZE", "20"))
        self._upsert_semaphore = asyncio.Semaphore(self.max_concurrent_upserts)

        # Qdrant endpoint is required for production service
        if require_endpoint and not self.qdrant_endpoint:
            raise ValueError(
                "QDRANT_ENDPOINT environment variable is required but not set"
            )

        # Initialize Qdrant client only if endpoint is available
        if self.qdrant_endpoint:
            try:
                qdrant_api_key = os.getenv("QDRANT_API_KEY")

                self.qdrant_client = AsyncQdrantClient(
                    url=self.qdrant_endpoint,
                    timeout=120,  # 2 minute timeout for large operations
                    api_key=qdrant_api_key,
                )
                logging.info(
                    "Async Qdrant client initialized: %s", self.qdrant_endpoint
                )
            except Exception as e:
                if require_endpoint:
                    logging.error("Failed to initialize Qdrant client: %s", e)
                    raise ValueError(f"Failed to initialize Qdrant client: {e}")
                else:
                    logging.warning(
                        "Qdrant client initialization skipped in local mode: %s", e
                    )
        else:
            logging.info("Qdrant client initialization skipped (local mode)")

    async def initialize(self) -> bool:
        """
        Initialize the search indexer, ensuring the Qdrant collection exists with proper schema.

        This method must be called after creating the QdrantIndex instance and before
        performing any indexing or search operations. It creates the collection with
        the appropriate vector configurations for ColPali embeddings if it doesn't exist.

        Args:
            vectors_config: Optional dict defining vector configurations. If None, uses default config.

        Returns:
            bool: True if initialization successful, False otherwise
        """
        if self.qdrant_client:
            return await self._ensure_collection_exists()
        return True

    @staticmethod
    def _return_false_on_retry_error(retry_state: RetryCallState) -> bool:
        """Return False when retries are exhausted."""
        return False

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_fixed(0.5),
        retry=retry_if_exception_type(Exception),
        retry_error_callback=_return_false_on_retry_error,
    )
    async def _ensure_collection_exists(self) -> bool:
        """
        Ensure the Qdrant collection exists with the correct multi-vector schema.

        Creates a collection optimized for ColPali embeddings with three vector types:
        - "original": Raw patch embeddings with HNSW disabled for exact search
        - "mean_pooling_rows": Row-wise pooled embeddings for row-based retrieval
        - "mean_pooling_columns": Column-wise pooled embeddings for column-based retrieval

        The configuration follows Qdrant's recommendations for large-scale PDF retrieval
        with multi-vector comparisons using MAX_SIM strategy.

        Args:
            vectors_config: Optional dict defining vector configurations. If None, uses default config.

        Returns:
            bool: True if collection exists or was created successfully, False otherwise
        """
        try:
            collections_response = await self.qdrant_client.get_collections()  # type: ignore[union-attr]
            existing_collections = [c.name for c in collections_response.collections]

            if self.collection_name in existing_collections:
                logging.info(
                    "Qdrant collection '%s' already exists", self.collection_name
                )
                return True

            # Create collection with multi-vector configuration for ColPali embeddings
            # Configuration mirrors setup from: https://qdrant.tech/documentation/advanced-tutorials/pdf-retrieval-at-scale/
            await self.qdrant_client.create_collection(  # type: ignore[union-attr]
                collection_name=self.collection_name,
                vectors_config=self.vectors_config,
                on_disk_payload=True,  # Always store payloads on disk to reduce memory usage
                # Optimizer configuration for large-scale document collections
                optimizers_config=models.OptimizersConfigDiff(
                    deleted_threshold=0.2,  # Trigger optimization when 20% deleted
                    vacuum_min_vector_number=1000,  # Minimum vectors before vacuum
                    default_segment_number=0,  # Auto-determine segment count
                    flush_interval_sec=5,  # Flush to disk every 5 seconds
                    max_optimization_threads=1,  # Single thread for optimization
                ),
                # HNSW configuration for vectors that use it (not "original")
                hnsw_config=models.HnswConfigDiff(
                    m=16,  # Number of bi-directional links per node
                    ef_construct=100,  # Size of dynamic candidate list
                    full_scan_threshold=10000,  # Use full scan for collections smaller than this
                    max_indexing_threads=0,  # Auto-determine indexing threads
                ),
            )

            logging.info(
                "Qdrant collection '%s' created successfully", self.collection_name
            )
            return True

        except Exception as e:
            logging.error("Failed to ensure Qdrant collection exists: %s", e)
            return False

    def _get_default_vectors_config(self) -> dict:
        """
        Get the default vector configuration for ColPali embeddings.

        Returns:
            dict: Default vectors_config with hierarchical, row, and column pooling
        """
        return {
            # Hierarchical patch embeddings - HNSW disabled, on disk for reranking only
            "hierarchical_pooled": models.VectorParams(
                size=128,  # ColPali embedding dimension
                distance=models.Distance.COSINE,
                on_disk=True,  # Reranking vector on disk
                multivector_config=models.MultiVectorConfig(
                    comparator=models.MultiVectorComparator.MAX_SIM
                ),
                hnsw_config=models.HnswConfigDiff(
                    m=0  # Disable HNSW indexing - only used for reranking
                ),
            ),
            # Column-wise aggregated embeddings with binary quantization for fast prefetch
            "mean_pooled_columns": models.VectorParams(
                size=128,
                distance=models.Distance.COSINE,
                on_disk=False,  # Discard full vectors since we use quantization
                multivector_config=models.MultiVectorConfig(
                    comparator=models.MultiVectorComparator.MAX_SIM
                ),
                quantization_config=models.BinaryQuantization(
                    binary=models.BinaryQuantizationConfig(
                        always_ram=True  # Keep quantized vectors in RAM for speed
                    ),
                ),
            ),
            # Row-wise aggregated embeddings with binary quantization for fast prefetch
            "mean_pooled_rows": models.VectorParams(
                size=128,
                distance=models.Distance.COSINE,
                on_disk=False,  # Discard full vectors since we use quantization
                multivector_config=models.MultiVectorConfig(
                    comparator=models.MultiVectorComparator.MAX_SIM
                ),
                quantization_config=models.BinaryQuantization(
                    binary=models.BinaryQuantizationConfig(
                        always_ram=True  # Keep quantized vectors in RAM for speed
                    ),
                ),
            ),
        }

    @staticmethod
    def _return_false_on_index_error(retry_state: RetryCallState) -> bool:
        """Return False when retries are exhausted for indexing."""
        return False

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_fixed(0.5),
        retry=retry_if_exception_type(Exception),
        retry_error_callback=_return_false_on_index_error,
    )
    async def index_embeddings(self, processed_pages: List[ProcessedPage]) -> bool:
        """
        Index embeddings to Qdrant with multi-vector structure.

        Takes a list of ProcessedPage objects containing ColPali embeddings and indexes
        them into Qdrant with multiple vector representations (original, row pooling,
        column pooling). Each page is stored as a single point with named vectors
        corresponding to the different embedding strategies.

        Args:
            processed_pages (List[ProcessedPage]): List of ProcessedPage models containing
                embeddings and metadata for document pages

        Returns:
            bool: True if indexing successful, False otherwise

        Raises:
            Exception: Raised after retries exhausted
        """
        if not self.qdrant_client:
            logging.warning("Qdrant client not initialized - skipping indexing")
            return True

        points = []
        for processed_page in processed_pages:
            # Validate embeddings exist
            if not processed_page.embeddings:
                logging.error(
                    "Missing embeddings for page %s: embeddings=%s",
                    processed_page.page_id,
                    processed_page.embeddings,
                )
                continue

            # Create Qdrant point structure with named vectors
            # Map embeddings to the collection's vector configuration
            vector_dict = {}

            # Map embeddings to "original" vector
            if "embeddings" in processed_page.embeddings:
                # Convert to numpy array with float32 dtype for Qdrant
                vector_dict["original"] = np.asarray(
                    processed_page.embeddings["embeddings"],
                    dtype=np.float32,
                )

            # Map hierarchical patch embeddings to "hierarchical_pooling" vector
            if "hierarchical_pooled_embeddings" in processed_page.embeddings:
                # Convert to numpy array with float32 dtype for Qdrant
                vector_dict["hierarchical_pooled"] = np.asarray(
                    processed_page.embeddings["hierarchical_pooled_embeddings"],
                    dtype=np.float32,
                )

            # Map pooled embeddings to their respective vectors
            if "mean_row_pooled_embeddings" in processed_page.embeddings:
                # Convert to numpy array with float32 dtype for Qdrant
                vector_dict["mean_pooled_rows"] = np.asarray(
                    processed_page.embeddings["mean_row_pooled_embeddings"],
                    dtype=np.float32,
                )

            if "mean_column_pooled_embeddings" in processed_page.embeddings:
                # Convert to numpy array with float32 dtype for Qdrant
                vector_dict["mean_pooled_columns"] = np.asarray(
                    processed_page.embeddings["mean_column_pooled_embeddings"],
                    dtype=np.float32,
                )

            if not vector_dict:
                logging.error(
                    "No valid embeddings found for page %s", processed_page.page_id
                )
                continue

            # Create Qdrant point with multi-vector embeddings and metadata
            payload = {
                "document_id": processed_page.document_id,
                "page_number": processed_page.page_number,
                "filename": processed_page.filename,  # Original filename
                "file_extension": processed_page.file_extension,  # File extension
                "text_content": processed_page.text_content,  # Extracted text content
                "page_image_url": processed_page.page_image_url,  # Blob storage URL for page image
                "indexed_at": processed_page.indexed_at.isoformat(),
                "page_id": processed_page.page_id,
            }

            # Add blob_url to payload if available
            if processed_page.blob_url:
                payload["blob_url"] = processed_page.blob_url

            # Automatically add all metadata fields as top-level fields in the payload
            if processed_page.metadata:
                for key, value in processed_page.metadata.items():
                    # Ensure field name is valid for Qdrant (no spaces, special characters)
                    field_name = key.lower().replace(" ", "_").replace("-", "_")
                    # Only add if not already present and value is not None
                    if field_name not in payload and value is not None:
                        # Ensure value is JSON serializable
                        try:
                            json.dumps(value)  # Test serialization
                            payload[field_name] = value
                        except (TypeError, ValueError):
                            # Convert to string if not serializable
                            payload[field_name] = str(value)
                            logging.debug(
                                "Converted metadata field '%s' to string for page %s",
                                field_name,
                                processed_page.page_id,
                            )

            point = models.PointStruct(
                id=processed_page.page_id,
                vector=vector_dict,  # Named vectors for different embedding strategies
                payload=payload,
            )

            points.append(point)

        # Batch upsert to Qdrant with concurrency control and batching
        if points:
            # Split points into batches
            batches = [
                points[i : i + self.upsert_batch_size]
                for i in range(0, len(points), self.upsert_batch_size)
            ]

            async def upsert_batch(batch: list) -> None:
                """Upsert a single batch with semaphore control."""
                async with self._upsert_semaphore:
                    await self.qdrant_client.upsert(
                        collection_name=self.collection_name,
                        points=batch,
                        wait=True,
                    )

            # Execute all batches concurrently (limited by semaphore)
            await asyncio.gather(*[upsert_batch(batch) for batch in batches])
            logging.info(
                "Indexed %s embeddings to Qdrant in %s batches",
                len(points),
                len(batches),
            )

        return True

    @staticmethod
    def _return_false_on_delete_error(retry_state: RetryCallState) -> bool:
        """Return False when retries are exhausted for deletion."""
        return False

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_fixed(0.5),
        retry=retry_if_exception_type(Exception),
        retry_error_callback=_return_false_on_delete_error,
    )
    async def delete_document_pages(self, document_id: str) -> bool:
        """
        Delete all pages for a document from Qdrant.

        Removes all points (pages) associated with a specific document ID using
        a filter-based deletion. This is useful for document updates or cleanup.

        Args:
            document_id (str): Document ID to delete all pages for

        Returns:
            bool: True if deletion successful, False otherwise

        Raises:
            Exception: Raised after retries exhausted
        """
        if not self.qdrant_client:
            logging.warning("Qdrant client not initialized - skipping deletion")
            return True

        # Delete all points matching the document_id filter
        await self.qdrant_client.delete(
            collection_name=self.collection_name,
            points_selector=models.FilterSelector(
                filter=models.Filter(
                    must=[
                        models.FieldCondition(
                            key="document_id",
                            match=models.MatchValue(value=document_id),
                        )
                    ]
                )
            ),
            wait=True,  # Wait for deletion to complete
        )

        logging.info("Deleted pages for document '%s' from Qdrant", document_id)
        return True

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_fixed(0.5),
        retry=retry_if_exception_type(Exception),
        retry_error_callback=_return_false_on_delete_error,
    )
    async def delete_orphan_pages(
        self, document_id: str, max_valid_page_number: int
    ) -> bool:
        """
        Delete orphan pages for a document from Qdrant.

        Removes pages with page_number > max_valid_page_number for a specific
        document. This is useful for zero-downtime re-indexing when a document
        has fewer pages than before (e.g., pages removed from PDF).

        This approach provides zero-downtime during re-indexing:
        1. Upsert new/updated pages first (document remains searchable)
        2. Delete orphan pages that no longer exist in the source document

        Args:
            document_id (str): Document ID to clean up orphan pages for
            max_valid_page_number (int): Maximum valid page number (1-based).
                Pages with page_number > this value will be deleted.

        Returns:
            bool: True if deletion successful (or no orphans found), False otherwise

        Raises:
            Exception: Raised after retries exhausted
        """
        if not self.qdrant_client:
            logging.warning("Qdrant client not initialized - skipping orphan deletion")
            return True

        # Delete all points matching document_id AND page_number > max_valid_page_number
        await self.qdrant_client.delete(
            collection_name=self.collection_name,
            points_selector=models.FilterSelector(
                filter=models.Filter(
                    must=[
                        models.FieldCondition(
                            key="document_id",
                            match=models.MatchValue(value=document_id),
                        ),
                        models.FieldCondition(
                            key="page_number",
                            range=models.Range(gt=max_valid_page_number),
                        ),
                    ]
                )
            ),
            wait=True,  # Wait for deletion to complete
        )

        logging.info(
            "Deleted orphan pages (page_number > %d) for document '%s' from Qdrant",
            max_valid_page_number,
            document_id,
        )
        return True

    async def close(self):
        """
        Close Qdrant client connection and cleanup resources.

        Should be called when the QdrantIndex instance is no longer needed
        to properly cleanup async connections and prevent resource leaks.
        """
        if self.qdrant_client:
            await self.qdrant_client.close()
            logging.info("Qdrant client connection closed")
